[project]
name = "colossal-conversor"
version = "4.0.0"
description = "Offline multi-format file conversion utility"
authors = [{ name = "Sxnnyside Project" }]
readme = "README.md"
license = { file = "LICENSE" }
requires-python = ">=3.10"

dependencies = [
    "PySide6",
    "pillow",
    "ffmpeg-python",
    "pydub",
    "python-i18n",
    "cairosvg",
    "pillow-heif"
]

[project.scripts]
colossal = "colossal.main:main"
install_audio = "scripts.install_audio_dependencies:main"
install_video = "scripts.install_video_dependencies:main"
install_image = "scripts.install_image_dependencies:main"
install_document = "scripts.install_document_dependencies:main"
install_sheet = "scripts.install_sheet_dependencies:main"
install_slide = "scripts.install_slide_dependencies:main"