from __future__ import annotations

from enum import Enum
from pathlib import Path

class JobStatus(Enum):
    Pending = ...
    Running = ...
    Cancelling = ...
    Cancelled = ...
    Completed = ...
    Failed = ...
    Partial = ...

class Cardinality(Enum):
    OneToOne = ...
    OneToMany = ...
    ManyToOne = ...
    ManyToMany = ...

class ArtifactRole(Enum):
    Input = ...
    Intermediate = ...
    Output = ...
    Auxiliary = ...

class ErrorCode(Enum):
    InvalidRequest = ...
    UnsupportedFormat = ...
    CapabilityNotFound = ...
    MissingDependency = ...
    ExecutionFailed = ...
    Cancelled = ...
    OutputFailure = ...
    PipelineFailure = ...
    Timeout = ...
    Unknown = ...

class Error:
    def __init__(
        self,
        code: ErrorCode,
        message: str,
        details: str | None = None,
        stage_index: int | None = None,
    ) -> None: ...
    @property
    def code(self) -> ErrorCode: ...
    @property
    def message(self) -> str: ...
    @property
    def details(self) -> str | None: ...
    @property
    def stage_index(self) -> int | None: ...

class Artifact:
    path: Path
    format_id: str
    role: ArtifactRole
    size_bytes: int | None
    def __init__(
        self,
        path: Path | str = ...,
        format_id: str = ...,
        role: ArtifactRole = ...,
        size_bytes: int | None = None,
    ) -> None: ...
    def exists(self) -> bool: ...
    def filename(self) -> str: ...

class Capability:
    id: str
    name: str
    engine_id: str
    input_formats: set[str]
    output_formats: set[str]
    requirements: list[str]
    cardinality: Cardinality
    fidelity: str
    def __init__(self) -> None: ...
    def supports(self, in_fmt: str, out_fmt: str) -> bool: ...

class Request:
    id: str
    input_artifacts: list[Artifact]
    output_format_id: str
    destination_path: Path
    options: dict[str, str]
    def __init__(self) -> None: ...
    @property
    def is_multi_input(self) -> bool: ...

class PipelineStage:
    stage_index: int
    name: str
    capability: Capability
    input_format_id: str
    output_format_id: str
    options: dict[str, str]
    def __init__(self) -> None: ...

class Pipeline:
    stages: list[PipelineStage]
    def __init__(self) -> None: ...
    @property
    def stage_count(self) -> int: ...
    @property
    def is_multi_stage(self) -> bool: ...
    def validate(self) -> None: ...

class Job:
    def __init__(self, id: str, request: Request, pipeline: Pipeline) -> None: ...
    @property
    def id(self) -> str: ...
    @property
    def request(self) -> Request: ...
    @property
    def pipeline(self) -> Pipeline: ...
    @property
    def status(self) -> JobStatus: ...
    @property
    def progress(self) -> float: ...
    @property
    def produced_artifacts(self) -> list[Artifact]: ...
    @property
    def intermediate_artifacts(self) -> list[Artifact]: ...
    @property
    def errors(self) -> list[Error]: ...
    def start(self) -> None: ...
    def update_progress(self, value: float) -> None: ...
    def request_cancel(self) -> None: ...
    def mark_cancelled(self) -> None: ...
    def complete(self, artifacts: list[Artifact]) -> None: ...
    def fail(self, error: Error) -> None: ...
    @property
    def duration_seconds(self) -> float | None: ...

class Result:
    job_id: str
    status: JobStatus
    output_artifacts: list[Artifact]
    error: Error | None
    duration_seconds: float
    def __init__(self) -> None: ...
    @property
    def is_success(self) -> bool: ...
    @property
    def is_cancelled(self) -> bool: ...
    @property
    def is_failed(self) -> bool: ...

class ToolDiscovery:
    @staticmethod
    def instance() -> ToolDiscovery: ...
    def register_custom_path(self, tool_name: str, path: Path | str) -> None: ...
    def add_search_directory(self, dir: Path | str) -> None: ...
    def find_tool(self, tool_name: str) -> Path | None: ...
    def require_tool(self, tool_name: str, stage_index: int | None = None) -> Path: ...
    def clear_cache(self) -> None: ...

class MediaMetadata:
    format_id: str
    mime_type: str
    file_size_bytes: int
    width: int | None
    height: int | None
    channels: int | None
    sample_rate: int | None
    duration_seconds: float | None
    page_count: int | None
    properties: dict[str, str]
    def __init__(self) -> None: ...

class FormatDetector:
    @staticmethod
    def detect_format(path: Path | str) -> str: ...
    @staticmethod
    def detect_mime(path: Path | str) -> str: ...

class MediaInspector:
    @staticmethod
    def inspect(path: Path | str) -> MediaMetadata: ...

class ProcessResult:
    exit_code: int
    stdout_text: str
    stderr_text: str
    duration_seconds: float
    cancelled: bool
    def __init__(self) -> None: ...
    @property
    def is_success(self) -> bool: ...

class ProcessSupervisor:
    @staticmethod
    def execute(
        command: list[str],
        cwd: Path | str | None = None,
        timeout_seconds: float | None = None,
    ) -> ProcessResult: ...

class NativeRuntime:
    def __init__(self, thread_count: int = 4, temp_dir: Path | str = "") -> None: ...
    def execute_job(self, job: Job) -> Result: ...
    def execute_batch(self, jobs: list[Job]) -> list[Result]: ...
    def has_engine(self, engine_id: str) -> bool: ...
    def shutdown(self) -> None: ...

def win_quote_argument(arg: str) -> str: ...
def win_build_command_line(args: list[str]) -> str: ...
